validation_data:
  relative_pose: true

unet_additional_kwargs:
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  motion_module_mid_block: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : false

  use_epi_module              : true
  epi_module_resolutions      : [ 1,2,4,8 ]
  epi_module_mid_block: false  
  epi_module_kwargs:  
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Epi_Self", "Epi_Self" ]
    epi_position_encoding              : true
    epi_position_encoding_feat_max_size: 64
    epi_position_encoding_F_mat_size   : 256
    epi_rand_slope_ff                  : true
    zero_initialize                    : true

pose_encoder_kwargs:
  downscale_factor: 8
  channels: [320, 640, 1280, 1280]
  nums_rb: 2
  cin: 384
  ksize: 1
  sk: true
  use_conv: false
  compression_factor: 1
  temporal_attention_nhead: 8
  attention_block_types: ["Temporal_Self", ]
  temporal_position_encoding: true
  temporal_position_encoding_max_len: 16

attention_processor_kwargs:
  add_spatial: false
  spatial_attn_names: 'attn1'
  add_temporal: true
  temporal_attn_names: '0'
  pose_feature_dimensions: [320, 640, 1280, 1280]
  query_condition: true
  key_value_condition: true
  scale: 1.0

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false